name: 'SSH Socket Setup'
description: 'Setup an SSH socket with a private key'
author: Sourcetoad
branding:
  color: green
  icon: dollar-sign

inputs:
  host:
    description: 'remote hostname'
    required: true
  port:
    description: 'ssh port'
    required: false
  socket-path:
    description: 'path at which to create socket'
    required: true
  key:
    description: 'ssh private key'
    required: true
  lifetime_in_seconds:
    description: 'how many seconds to keep socket live'
    required: false
    default: '600'
outputs:
  socket-path:
    description: 'path at which socket was created'
runs:
  using: 'node12'
  main: 'dist/index.js'
