name: ci
on: push

jobs:
  update:
    runs-on: ubuntu-22.04
    name: Node 22

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Test Itself (Random Socket)
        id: ssh-socket-action-random
        uses: ./
        with:
          host: github.com
          key: ${{ secrets.BASE64_INTENTIONAL_EXAMPLE_PUBLIC_SECRET_KEY }}

      - name: Use SSH socket (Random Socket)
        run: ls -l "${{ steps.ssh-socket-action-random.outputs.socket-path }}"

      - name: Test Itself (Specified Socket)
        id: ssh-socket-action-specified
        uses: ./
        with:
          host: github.com
          socket-path: '/tmp/ssh_agent.sock'
          key: ${{ secrets.BASE64_INTENTIONAL_EXAMPLE_PUBLIC_SECRET_KEY }}

      - name: Use SSH socket (Specified Socket)
        run: ls -l "${{ steps.ssh-socket-action-specified.outputs.socket-path }}"
