name: ci
on: push

jobs:
  update:
    runs-on: ubuntu-22.04
    name: Node 16

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install

      - run: yarn build
