name: dist
on:
  push:
    branches:
      - master

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    name: Commit Dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install

      - run: yarn build

      - name: Commit updated dist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dist
          file_pattern: dist/
