name: dist
on:
  push:
    branches:
      - master

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    name: Commit Dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: Commit updated dist
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update dist
          file_pattern: dist/
