name: ci
on: push

jobs:
  update:
    runs-on: ubuntu-22.04
    name: Commit Dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: yarn install
        run: yarn install

      - name: yarn install
        run: yarn build

      - name: Commit updated dist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dist
          file_pattern: dist/
